### PR TITLE
Increment installers

### PR DESCRIPTION
**Pull request by hobu**
* Anaconda3-2023.0
* Miniconda3-py310_23.11.0-2
* Mambaforge-23.11.0

I had an issue where I was getting conflicting SSL/Curl from some of the packages I was using and updating the base to new installers fixed it.

### CODE REVIEW

**Comment by jaimergp** [comment]
Thanks! Unfortunately, we need to ensure that all the installers use Python 3.10. I don't think that's the case for the added Anaconda version ([see table](https://docs.anaconda.com/free/anaconda/allpkglists/2023.09-0/#pkg-table)). Can you double check with the others?

**Comment by hobu** [comment]
I've never used Anaconda, but looking through the list, it seems we'll have to just leave that installer alone. What's currently listed is the last `python=3.10`.

I have been testing the mambaforge one with success. If anyone else is able, please test with

```
!pip install -U https://github.com/hobu/condacolab/archive/0.1.x.tar.gz
```

**Comment by jaimergp** [comment]
Thanks!

**Comment by jaimergp** [comment]
Released in 0.1.9

**Pull request merged**
